import 'package:flutter/material.dart';
import 'package:web_appllication/model/user_model/quality_checklistModel.dart';
import 'package:web_appllication/widgets/widgets_user/user_style.dart';
import 'activity_headings.dart';

HeaderValue(String title, String hintValue, String changeValue) {
  return Container(
    color: lightblue,
    width: 625,
    padding: const EdgeInsets.all(3),
    child: Row(
      mainAxisAlignment: MainAxisAlignment.spaceAround,
      children: [
        Container(
            width: 150,
            child: Text(
              title,
            )),
        const SizedBox(width: 5),
        Expanded(
            child: Container(
                height: 30,
                child: true
                    // 'widget.isHeader!'
                    ? TextFormField(
                        decoration: const InputDecoration(
                            contentPadding:
                                EdgeInsets.only(top: 0, bottom: 0, left: 5)),
                        initialValue: hintValue,
                        style: const TextStyle(fontSize: 15),
                        // onChanged: (value) {
                        //   changeValue = value;
                        // },
                        onSaved: (newValue) {
                          changeValue = newValue.toString();
                        },
                      )
                    : Container(
                        width: 120,
                        decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(5),
                            border: Border.all(color: blue)),
                        child: Text(hintValue)))),
      ],
    ),
  );
}

// EXCAVATION ACTIVITY DATA
List<QualitychecklistModelUser> excavation_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: civil_exc_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: civil_exc_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: civil_exc_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: civil_exc_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: civil_exc_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: civil_exc_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: civil_exc_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: civil_exc_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: civil_exc_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: civil_exc_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: civil_exc_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: civil_exc_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: civil_exc_activity_data[12],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: civil_exc_activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 15,
      checklist: civil_exc_activity_data[14],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// BACKFILLING ACTIVITY DATA
List<QualitychecklistModelUser> backfilling_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: civil_bf_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: civil_bf_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: civil_bf_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: civil_bf_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: civil_bf_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: civil_bf_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: civil_bf_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: civil_bf_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: civil_bf_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: civil_bf_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: civil_bf_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: civil_bf_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: civil_bf_activity_data[12],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: civil_bf_activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 15,
      checklist: civil_bf_activity_data[14],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 16,
      checklist: civil_bf_activity_data[15],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// BRICK & BLOCK MASSONARY ACTIVITY DATA
List<QualitychecklistModelUser> massonary_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: civil_mass_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: civil_mass_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: civil_mass_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: civil_mass_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: civil_mass_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: civil_mass_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: civil_mass_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: civil_mass_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: civil_mass_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: civil_mass_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: civil_mass_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: civil_mass_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: civil_mass_activity_data[12],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: civil_mass_activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 15,
      checklist: civil_mass_activity_data[14],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 16,
      checklist: civil_mass_activity_data[15],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// BLDG DOORS, WINDOWS, HARDWARE, GLAZING ACTIVITY DATA
List<QualitychecklistModelUser> glazzing_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: civil_dwg_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: civil_dwg_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: civil_dwg_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: civil_dwg_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: civil_dwg_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: civil_dwg_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: civil_dwg_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: civil_dwg_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: civil_dwg_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: civil_dwg_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: civil_dwg_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: civil_dwg_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: civil_dwg_activity_data[12],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: civil_dwg_activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 15,
      checklist: civil_dwg_activity_data[14],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 16,
      checklist: civil_dwg_activity_data[15],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 17,
      checklist: civil_dwg_activity_data[16],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 18,
      checklist: civil_dwg_activity_data[17],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// FALSE CEILING ACTIVITY DATA
List<QualitychecklistModelUser> ceilling_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: civil_fc_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: civil_fc_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: civil_fc_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: civil_fc_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: civil_fc_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: civil_fc_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: civil_fc_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: civil_fc_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: civil_fc_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: civil_fc_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: civil_fc_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: civil_fc_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: civil_fc_activity_data[12],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: civil_fc_activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 15,
      checklist: civil_fc_activity_data[14],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 16,
      checklist: civil_fc_activity_data[15],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// FLOORING & TILING ACTIVITY DATA
List<QualitychecklistModelUser> florring_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: civil_ft_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: civil_ft_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: civil_ft_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: civil_ft_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: civil_ft_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: civil_ft_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: civil_ft_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: civil_ft_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: civil_ft_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: civil_ft_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: civil_ft_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: civil_ft_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// GROUTING INSPECTION ACTIVITY DATA
List<QualitychecklistModelUser> inspection_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: civil_gi_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: civil_gi_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: civil_gi_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: civil_gi_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: civil_gi_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: civil_gi_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: civil_gi_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: civil_gi_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: civil_gi_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: civil_gi_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: civil_gi_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: civil_gi_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: civil_gi_activity_data[12],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: civil_gi_activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// IRONITE FLORRING ACTIVITY DATA
List<QualitychecklistModelUser> ironite_florring_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: civil_if_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: civil_if_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: civil_if_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: civil_if_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: civil_if_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: civil_if_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: civil_if_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: civil_if_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: civil_if_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: civil_if_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: civil_if_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: civil_if_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: civil_if_activity_data[12],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: civil_if_activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// PAINTING ACTIVITY DATA
List<QualitychecklistModelUser> painting_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: civil_painting_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: civil_painting_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: civil_painting_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: civil_painting_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: civil_painting_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: civil_painting_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: civil_painting_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: civil_painting_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: civil_painting_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: civil_painting_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: civil_painting_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: civil_painting_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: civil_painting_activity_data[12],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: civil_painting_activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 15,
      checklist: civil_painting_activity_data[14],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 16,
      checklist: civil_painting_activity_data[15],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 17,
      checklist: civil_painting_activity_data[16],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// PAVING ACTIVITY DATA
List<QualitychecklistModelUser> paving_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: civil_paving_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: civil_paving_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: civil_paving_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: civil_paving_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: civil_paving_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: civil_paving_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: civil_paving_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: civil_paving_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: civil_paving_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: civil_paving_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: civil_paving_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// WCR ACTIVITY DATA
List<QualitychecklistModelUser> roofing_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: civil_wcr_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: civil_wcr_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: civil_wcr_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: civil_wcr_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: civil_wcr_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: civil_wcr_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: civil_wcr_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: civil_wcr_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: civil_wcr_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: civil_wcr_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: civil_wcr_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: civil_wcr_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: civil_wcr_activity_data[12],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: civil_wcr_activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 15,
      checklist: civil_wcr_activity_data[14],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 16,
      checklist: civil_wcr_activity_data[15],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 17,
      checklist: civil_wcr_activity_data[16],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 18,
      checklist: civil_wcr_activity_data[17],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 19,
      checklist: civil_wcr_activity_data[18],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// PROOFING ACTIVITY DATA
List<QualitychecklistModelUser> proofing_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: civil_wp_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: civil_wp_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: civil_wp_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: civil_wp_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: civil_wp_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: civil_wp_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: civil_wp_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: civil_wp_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: civil_wp_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: civil_wp_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: civil_wp_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: civil_wp_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: civil_wp_activity_data[12],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: civil_wp_activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 15,
      checklist: civil_wp_activity_data[14],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 16,
      checklist: civil_wp_activity_data[15],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 17,
      checklist: civil_wp_activity_data[16],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// All Electrical List

// PSS ACTIVITY DATA
List<QualitychecklistModelUser> getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: activity_data[12],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 15,
      checklist: activity_data[14],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 16,
      checklist: activity_data[15],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 17,
      checklist: activity_data[16],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 18,
      checklist: activity_data[17],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 19,
      checklist: activity_data[18],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 20,
      checklist: activity_data[19],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 21,
      checklist: activity_data[20],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 22,
      checklist: activity_data[21],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 23,
      checklist: activity_data[22],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// RMU ACTIVITY DATA
List<QualitychecklistModelUser> rmu_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: rmu_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: rmu_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: rmu_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: rmu_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: rmu_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: rmu_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: rmu_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: rmu_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: rmu_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: rmu_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: rmu_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: rmu_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: rmu_activity_data[12],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: rmu_activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 15,
      checklist: rmu_activity_data[14],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 17,
      checklist: rmu_activity_data[16],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 18,
      checklist: rmu_activity_data[17],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 19,
      checklist: rmu_activity_data[18],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 20,
      checklist: rmu_activity_data[19],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 21,
      checklist: rmu_activity_data[20],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// CT ACTIVITY DATA
List<QualitychecklistModelUser> ct_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: ct_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: ct_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: ct_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: ct_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: ct_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: ct_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: ct_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: ct_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: ct_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: ct_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: ct_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: ct_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: ct_activity_data[12],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: ct_activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 15,
      checklist: ct_activity_data[14],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 17,
      checklist: ct_activity_data[16],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 18,
      checklist: ct_activity_data[17],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 19,
      checklist: ct_activity_data[18],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 20,
      checklist: ct_activity_data[19],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 21,
      checklist: ct_activity_data[20],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 22,
      checklist: ct_activity_data[21],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// CMU ACTIVITY DATA
List<QualitychecklistModelUser> cmu_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: cmu_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: cmu_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: cmu_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: cmu_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: cmu_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: cmu_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: cmu_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: cmu_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: cmu_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: cmu_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: cmu_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: cmu_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: cmu_activity_data[12],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: cmu_activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 15,
      checklist: cmu_activity_data[14],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 17,
      checklist: cmu_activity_data[16],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 18,
      checklist: cmu_activity_data[17],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 19,
      checklist: cmu_activity_data[18],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 20,
      checklist: cmu_activity_data[19],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 21,
      checklist: cmu_activity_data[20],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 22,
      checklist: cmu_activity_data[21],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 23,
      checklist: cmu_activity_data[22],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// ACDB ACTIVITY DATA
List<QualitychecklistModelUser> acdb_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: acdb_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: acdb_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: acdb_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: acdb_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: acdb_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: acdb_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: acdb_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: acdb_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: acdb_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: acdb_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: acdb_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: acdb_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: acdb_activity_data[12],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: acdb_activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 15,
      checklist: acdb_activity_data[14],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 16,
      checklist: acdb_activity_data[15],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 17,
      checklist: acdb_activity_data[16],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 18,
      checklist: acdb_activity_data[17],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 19,
      checklist: acdb_activity_data[18],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 20,
      checklist: acdb_activity_data[19],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 21,
      checklist: acdb_activity_data[20],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 22,
      checklist: acdb_activity_data[21],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 23,
      checklist: acdb_activity_data[22],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 24,
      checklist: acdb_activity_data[23],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 25,
      checklist: acdb_activity_data[24],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// CI ACTIVITY DATA
List<QualitychecklistModelUser> ci_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: ci_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: ci_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: ci_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: ci_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: ci_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: ci_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: ci_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: ci_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: ci_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: ci_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: ci_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: acdb_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: ci_activity_data[12],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// CDI ACTIVITY DATA
List<QualitychecklistModelUser> cdi_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: cdi_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: cdi_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: cdi_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: cdi_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: cdi_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: cdi_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// MSP ACTIVITY DATA
List<QualitychecklistModelUser> msp_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: msp_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: msp_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: msp_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: msp_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: msp_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: msp_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: msp_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: msp_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: msp_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: msp_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: msp_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: msp_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: msp_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: msp_activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 15,
      checklist: msp_activity_data[14],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 16,
      checklist: msp_activity_data[15],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 17,
      checklist: msp_activity_data[16],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 18,
      checklist: msp_activity_data[17],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 18,
      checklist: msp_activity_data[17],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 19,
      checklist: msp_activity_data[18],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 20,
      checklist: msp_activity_data[19],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 21,
      checklist: msp_activity_data[20],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 23,
      checklist: msp_activity_data[22],
      responsibility: '',
      reference: '',
      observation: '',
    )
  ];
}

// CHARGER ACTIVITY DATA
List<QualitychecklistModelUser> charger_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: charger_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: charger_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: charger_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: charger_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: charger_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: charger_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: charger_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: charger_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: charger_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: charger_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: charger_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: charger_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: charger_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: charger_activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 15,
      checklist: charger_activity_data[14],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 16,
      checklist: charger_activity_data[15],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 17,
      checklist: charger_activity_data[16],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 18,
      checklist: charger_activity_data[17],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 18,
      checklist: charger_activity_data[17],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 19,
      checklist: charger_activity_data[18],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 20,
      checklist: charger_activity_data[19],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 21,
      checklist: charger_activity_data[20],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}

// EARTH PIT ACTIVITY DATA
List<QualitychecklistModelUser> earth_pit_getData() {
  return [
    QualitychecklistModelUser(
      srNo: 1,
      checklist: earth_pit_activity_data[0],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 2,
      checklist: earth_pit_activity_data[1],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 3,
      checklist: earth_pit_activity_data[2],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 4,
      checklist: earth_pit_activity_data[3],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 5,
      checklist: earth_pit_activity_data[4],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 6,
      checklist: earth_pit_activity_data[5],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 7,
      checklist: earth_pit_activity_data[6],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 8,
      checklist: earth_pit_activity_data[7],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 9,
      checklist: earth_pit_activity_data[8],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 10,
      checklist: earth_pit_activity_data[9],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 11,
      checklist: earth_pit_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 12,
      checklist: earth_pit_activity_data[11],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 13,
      checklist: earth_pit_activity_data[10],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 14,
      checklist: earth_pit_activity_data[13],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 15,
      checklist: earth_pit_activity_data[14],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 16,
      checklist: earth_pit_activity_data[15],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 17,
      checklist: earth_pit_activity_data[16],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 18,
      checklist: earth_pit_activity_data[17],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 19,
      checklist: earth_pit_activity_data[18],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 20,
      checklist: earth_pit_activity_data[19],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 21,
      checklist: earth_pit_activity_data[20],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 22,
      checklist: earth_pit_activity_data[21],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 23,
      checklist: earth_pit_activity_data[22],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 24,
      checklist: earth_pit_activity_data[23],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 25,
      checklist: earth_pit_activity_data[24],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 26,
      checklist: earth_pit_activity_data[25],
      responsibility: '',
      reference: '',
      observation: '',
    ),
    QualitychecklistModelUser(
      srNo: 27,
      checklist: earth_pit_activity_data[26],
      responsibility: '',
      reference: '',
      observation: '',
    ),
  ];
}
